version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:v1.9.1
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  fastapi-app:
    build: ./app
    ports:
      - "8080:8000"
    env_file:
      - .env
    depends_on:
      - qdrant

  nifi:
    image: apache/nifi:1.26.0
    ports:
      - "8443:8443"
    environment:
      - NIFI_WEB_HTTPS_HOST=0.0.0.0
    volumes:
      - ./data/raw_docs:/opt/nifi/data
    env_file:
      - .env
    depends_on:
      - fastapi-app

volumes:
  qdrant_storage: